# For parameter descriptions, please refer to the template parameter files for each node.

ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    publish_tf: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_plate
    world_frame: odom
    imu0: /bno055/imu
    imu1_config: [ false, false, false,  # Orientation
                   true, true, true,     # Angular velocity
                   false, false, false,  # Linear velocity (not provided by IMU)
                   true, true, true,     # Linear acceleration
                   false, false, false ]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: false
    imu1: /bno055_1/imu
    imu1_config: [ false, false, false,  # Orientation
                   true, true, true,     # Angular velocity
                   false, false, false,  # Linear velocity (not provided by IMU)
                   true, true, true,     # Linear acceleration
                   false, false, false ]
    imu1_differential: false
    imu1_queue_size: 10
    imu1_remove_gravitational_acceleration: true

    use_control: false

    process_noise_covariance: [ 1e-3, 1e-3, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3 ]

    initial_estimate_covariance: [ 1e-9, 1e-9, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]

ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_plate
    world_frame: odom
    imu0: /bno055/imu
    imu0_config: [ false, false, false,  # Orientation
                   true, true, true,     # Angular velocity
                   false, false, false,  # Linear velocity (not provided by IMU)
                   true, true, true,     # Linear acceleration
                   false, false, false ]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: false
    imu1: /bno055_1/imu
    imu1_config: [ false, false, false,  # Orientation
                   true, true, true,     # Angular velocity
                   false, false, false,  # Linear velocity (not provided by IMU)
                   true, true, true,     # Linear acceleration
                   false, false, false ]
    imu1_differential: false
    imu1_queue_size: 10
    imu1_remove_gravitational_acceleration: false


    twist0: /vel
    twist0_config: [ false, false, false,
                     false, false, false,
                     true,  true,  true,
                     false, false, false,
                     false, false, false ]
    twist0_queue_size: 3
    twist0_rejection_threshold: 0.10 # assuming m/s as units, the threshold is set some reasonable value beyond its accuracy.

    odom0: odometry/gps
    odom0_config: [ true,  true,  false,
                    false, false, false,
                    false, false, false,
                    false, false, false,
                    false, false, false ]
    odom0_queue_size: 2
    odom0_differential: false
    odom0_pose_rejection_threshold: 5.0
    odom0_twist_rejection_threshold: 1.0

    use_control: false

    process_noise_covariance: [ 1.0, 1.0, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3 ]

    initial_estimate_covariance: [ 1.0, 1.0, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]

navsat_transform:
  ros__parameters:
    frequency: 1.0
    delay: 3.0
    magnetic_declination_radians: 0.0429351  # For lat/long 55.944831, -3.186998
    yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
    zero_altitude: false
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
